@startuml driver-components
skinparam componentStyle rectangle

' These are our low-level hardware driver components.
' They communicate directly with the hardware control registers.
folder "drivers/" as devicedrivers {
    database "UART" as uartdriver {
        file uart.h
        file uart.c
        uart.h <..> uart.c
    }

    database "INT" as intdriver {
        file interrupts.h
        file interrupts.c
        interrupts.h <..> interrupts.c
    }

    database "ADC" as adcdriver {
        file adc.h
        file adc.c
        adc.h <..> adc.c
    }

    database "FVR" as fvrdriver {
        file fvr.h
        file fvr.c
        fvr.h <..> fvr.c
    }
}

' These represent the control registers on the PIC
node "Hardware Control Registers" {
    () EUSART
    () PPS
    () INT
    () PORTx
    () FVR
    () ADC
}

' Relationship between the device drivers and the hardware control registers.
uart.c --> PORTx
uart.c --> PPS
uart.c --> EUSART
uart.c --> INT

interrupts.c --> INT

fvr.c --> FVR

adc.c --> ADC

@enduml