@startuml library-components
skinparam componentStyle rectangle

' This is the main application.
folder "mode/<mode_name>/" {
    cloud "Mode Application" as powerpic
}


' These are the HAL components.
' They interact with the drivers to provide functionality to "Modes".
folder "lib/" {
    frame "Display" {
        file display.h
    }

    frame "Keypad" {
        file keypad.h
    }

    frame "Buttons" {
        file buttons.h
    }

    frame "Datetime" {
        file datetime.h
    }

    frame "Buzzer" {
        file buzzer.h
    }

    frame "Battery" {
        file battery.h
    }
}

component stdio.h

' Relationships between the main application and the HAL.
powerpic--> display.h
powerpic --> keypad.h
powerpic --> buttons.h
powerpic --> buzzer.h
powerpic --> battery.h
powerpic --> datetime.h
powerpic --> stdio.h
@enduml

@startuml library-drivers
skinparam componentStyle rectangle

' These are the HAL components.
' They interact with the drivers to provide functionality to "Modes".
folder "lib/" {
    frame "Display" {
        file display.h
        file display.c
        display.h <..> display.c
    }

    frame "Keypad" {
        file keypad.h
        file keypad.c
        keypad.h <..> keypad.c
    }

    frame "Buttons" {
        file buttons.h
        file buttons.c
        buttons.h <..> buttons.c
    }

    frame "Datetime" {
        file datetime.h
        file datetime.c
        datetime.h <..> datetime.c
    }

    frame "Buzzer" {
        file buzzer.h
        file buzzer.c
        buzzer.h <..> buzzer.c
    }

    frame "Battery" {
        file battery.h
        file battery.c
        battery.h <..> battery.c
    }
}

' These are our low-level hardware driver components.
' They communicate directly with the hardware control registers.
folder "drivers/" as devicedrivers {
    database "LCD" as lcddriver {
        file lcd.h
    }

    database "GPIO" as gpiodriver {
        file gpio.h
    }

    database "IOC" as iocdriver {
        file ioc.h 
    }

    database "PWM" as pwmdriver {
        file pwm.h
    }

    database "ADC" as adcdriver {
        file adc.h
    }

    database "RTCC" as rtccdriver {
        file rtcc.h
    }
}

' Relationships between the HAL and the device drivers.
display.c --> lcd.h
keypad.c --> ioc.h
keypad.c --> gpio.h
buttons.c --> ioc.h
buzzer.c --> pwm.h
battery.c --> adc.h
datetime.c --> rtcc.h
@enduml