/** @file mode_config_template.h
 * 
 * Configuration of which modes to include in the firmware.
 *
 * This file is auto-generated by the Makefile at compile time. It should not
 * be edited manually. To configure which modes are compiled into the firmware,
 * edit the 'modes.cfg' file.
 * 
 * The generated source file is located in src/modes/mode_config.h
*/

#ifndef _mode_config_template_h_
#define _mode_config_template_h_

#include "lib/mode.h"       // We need the mode typedefs
//MODE_INCLUDE

enum mode_app_index {
//MODE_INDEX
MODE_MAX_MODES,
};

mode_app_t *mode_list[MODE_MAX_MODES] = {
//MODE_LIST
};

#endif

// EOF //
